version: '3.8'

services:
  backend:
    build: ../backend
    container_name: elpolidev_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=elpolidev

  db:
    image: postgres:15
    container_name: elpolidev_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elpolidev
    ports:
      - "5432:5432"
